# Production environment configuration
# Live production settings

# Production settings
log_level: WARNING
debug: false

# Service configuration
host: "0.0.0.0"
port: 8000

# Production features
enable_monitoring: true
enable_alerting: true
enable_metrics: true
enable_profiling: false  # Disabled in production for performance

# Production limits
max_connections: 100
request_timeout: 30
rate_limit: 100
