# Staging environment configuration
# Pre-production environment settings

# Staging settings
log_level: INFO
debug: false

# Service configuration
host: "0.0.0.0"
port: 8000

# Staging features
enable_monitoring: true
enable_profiling: true
enable_metrics: true

# Staging limits (similar to production)
max_connections: 80
request_timeout: 30
rate_limit: 80
